Post http://89.87.125.211:4000/france HTTP/1.1
Content-Type: application/json

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2Njk5MTM2MzAsImlhdCI6MTY2OTgyNzIzMCwic3ViIjoyMjAyMjAwMH0.EjJrgStNYdWogPDxgNVmlA-Iva0ec0JU0hxu1_T2LME"
}