GET http://127.0.0.1:5000/infoSvg HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Njk4OTU3MjgsImlhdCI6MTY2OTgwOTMyOCwic3ViIjoyMjAyMjAwMH0.6QK0svj1pm2tYEwchLA4IkWUQ1fWrErxfE7sL_BJ03I"
}